apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingressbackend
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: python-uwsgi
          servicePort: 80
