apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.5
        ports:
        - containerPort: 5432 
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: shm-db
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: shm-db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shm-db
              key: password
