apiVersion: v1
kind: Service
metadata:
    name: postgres-database-server
    labels:
        run: postgresDb
spec:
    ports:
        - port: 5432
          protocol: TCP
    selector:
        app: postgres
