apiVersion: v1
data:
  POSTGRES_DB: example
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: "5432"
  POSTGRES_USER: test
kind: ConfigMap
metadata:
  name: postgres-postgres-database-conf
