apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
spec:
  template:
    spec:
      containers:
      - name: pytho-db-migrator
        image: 736336118102.dkr.ecr.eu-central-1.amazonaws.com/shm:python.uwsgi.1
        command: ["flask",  "db", "upgrade"]
        env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: shm-db
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shm-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shm-db
                  key: password
            - name: POSTGRES_HOST
              value: postgres-database-server
            - name: POSTGRES_PORT
              value: "5432"
      restartPolicy: Never
  backoffLimit: 4
