apiVersion: v1
kind: Service
metadata:
    name: python-uwsgi
    labels:
        run: python-uwsgi
spec:
    type: NodePort
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
    selector:
        run: python-uwsgi