apiVersion: v1
kind: Service
metadata:
    name: python-api-service
    labels:
        run: python-api
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
    selector:
        run: python-api
