version: '3'

services:
  typescript-nginx:
    container_name: typescript-nginx
    image: localhost:5000/typescript-nginx
    build:
      context: ../
      dockerfile: docker/typescript-nginx/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - python-nginx

  python-nginx:
    container_name: python-nginx
    image: localhost:5000/python-nginx
    build:
      context: ../
      dockerfile: docker/python-nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - python-uwsgi

  python-uwsgi:
    container_name: python-uwsgi
    image: localhost:5000/python-uwsgi
    build:
      context: ../
      dockerfile: docker/python-uwsgi/Dockerfile
    env_file: postgres/database.conf
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: postgres/database.conf
    ports:
      - 5432:5432
    volumes:
      - ../postgres:/var/lib/postgresql

  adminer:
   image: adminer
   ports:
     - 8080:8080

