version: '3.5'

services:
  typescript-nginx:
    container_name: typescript-nginx
    build:
      context: ../
      dockerfile: docker/typescript-nginx/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - python-nginx

  python-nginx:
    container_name: python-nginx
    build:
      context: ./
      dockerfile: python-nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - python-uwsgi

  python-uwsgi:
    container_name: python-uwsgi
    build:
      context: ../
      dockerfile: docker/python-uwsgi/Dockerfile
    env_file: postgres/database.conf
    expose:
      - 8080
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: postgres/database.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
