apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: typescript-nginx
  name: typescript-nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: typescript-nginx
    spec:
      containers:
      - image: docker_typescript-nginx
        name: typescript-nginx
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
