"""empty message

Revision ID: 350748cde6f4
Revises: e6d4ac8564fb
Create Date: 2019-04-02 14:10:12.331349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350748cde6f4'
down_revision = '42cf7f6532dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
