"""empty message

Revision ID: 3f0b0a0f76ec
Revises: 72a41f87e02d
Create Date: 2019-02-28 12:26:11.415596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0b0a0f76ec'
down_revision = '72a41f87e02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'archived')
    # ### end Alembic commands ###
