"""empty message

Revision ID: 99cca32ce758
Revises: 72a41f87e02d
Create Date: 2019-02-28 10:36:37.715586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cca32ce758'
down_revision = '72a41f87e02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'archived')
    # ### end Alembic commands ###
