"""empty message

Revision ID: bc15cb03227f
Revises: 72a41f87e02d
Create Date: 2019-02-28 11:13:00.588358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc15cb03227f'
down_revision = '72a41f87e02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('archived', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'archived')
    # ### end Alembic commands ###
