"""empty message

Revision ID: e6d4ac8564fb
Revises: 72a41f87e02d
Create Date: 2019-03-05 10:59:54.531509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d4ac8564fb'
down_revision = '72a41f87e02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=300), nullable=True),
    sa.Column('attitude', sa.String(length=300), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stakeholder')
    # ### end Alembic commands ###
